### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by harm-less** [sumitchawla/angularjs-filters#2]
Hello, 

Your filter library looks really handy at first hand. But when I wanted to use it in my project, I discovered it isn't a Bower repository.
It would be of help for me (and probably others) to to add it to Bower as a configurable dependency.

Harm

**Comment by sumitchawla** [comment]
Thanks for the suggestion. Added the package to bower. If you run into any issues do let me know

**Comment by harm-less** [comment]
Awesome, I'll add it to my project tomorrow and remove the code I copied from your repository from my core!
