### ISSUE TITLE
Names with special characters, such as hyphens and dots, are not allowed

### ISSUE THREAD

**Issue by domschmidt** [sumitchawla/angularjs-filters#4]
According to:
https://docs.angularjs.org/guide/filter

Names with special characters, such as hyphens and dots, are not allowed

The filters are not compatible with 1.3.15 anymore (previously used 1.3.0)

**Comment by harm-less** [comment]
+1
Simply camelizing the filter names like `string.replace` to `stringReplace` will solve the problem

**Comment by dozed** [comment]
Maybe the prefixes can be removed?

**Comment by harm-less** [comment]
That might have my vote as well. Less is more I guess.
